// One-time: replace inline style="…" attributes with utility/component classes.
import { readdirSync, readFileSync, writeFileSync } from 'fs'
const root = new URL('..', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')

// style content  ->  class(es) to add, or null to just remove the attribute
const MAP = {
  'transition-delay:0.05s': 'd1', 'transition-delay:0.1s': 'd2', 'transition-delay:0.15s': 'd3',
  'transition-delay:0.15000000000000002s': 'd3', 'transition-delay:0.2s': 'd4', 'transition-delay:0.25s': 'd5',
  'transition-delay:0.3s': 'd6', 'transition-delay:0.35s': 'd7', 'transition-delay:0.4s': 'd8', 'transition-delay:0.5s': 'd9',
  'background:var(--c-bg)': null,
  'background:var(--c-surface)': 'alt',
  'cursor:default': 'static-chip',
  'font-size:2rem;margin-bottom:0.75rem': 'emoji-lg',
  'color:var(--c-text-muted);margin-top:0.75rem': 'muted mt-3',
  'padding-top:calc(var(--nav-h) + clamp(2rem,5vw,3.5rem))': 'pt-nav',
  'color:#4ade80': 'eco-green',
  'margin-top:1rem': 'mt-4', 'margin-top:1.25rem': 'mt-5', 'margin-top:1.75rem': 'mt-7',
  'margin-bottom:1rem': 'mb-4', 'margin-bottom:1.5rem': 'mb-5',
  'color:var(--c-text-muted);margin-bottom:2rem': 'muted mb-6',
  'color:var(--c-text)': 'ink-text', 'color:var(--c-accent)': 'accent-text',
  'grid-template-columns:1fr': 'cols-1',
  'border:1px solid var(--c-border);border-radius:var(--radius-lg);overflow:hidden;margin-bottom:4rem': 'framed mb-8',
  'width:16px;height:16px;display:inline': 'ic-inline',
  'max-width:14ch': 'mw-14',
  'margin-top:2rem;padding:1.5rem;background:var(--c-surface-2);border:1px solid var(--c-border);border-radius:var(--radius-lg)': 'call-box',
  'justify-content:center': 'justify-center',
  'font-size:1.8rem;margin-bottom:0.5rem': 'form-h3',
  'font-size:1.6rem;margin-bottom:1.5rem': 'side-h2',
  'font-size:0.875rem;color:var(--c-text-muted);margin-bottom:0.75rem': 'call-box-label',
  'font-family:var(--font-display);font-size:1.6rem;font-weight:800;color:var(--c-accent)': 'call-box-phone',
  'display:flex;gap:1rem;margin-top:1.75rem;flex-wrap:wrap': 'btn-row',
  'display:flex;gap:1rem;flex-wrap:wrap;margin-top:1.75rem': 'btn-row',
  'color:var(--ink-2);margin:.9rem 0 1.8rem': 'eco-lead',
  'color:var(--c-text-muted);font-size:0.9rem;margin-bottom:1.75rem': 'form-sub',
}
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

// source pages only (post-*.html are regenerated by gen-blog)
const files = readdirSync(root).filter(f => f.endsWith('.html') && !f.startsWith('post-'))
let totalRemoved = 0
for (const f of files) {
  const path = root + '/' + f
  let html = readFileSync(path, 'utf8')
  const before = (html.match(/style="/g) || []).length
  for (const [style, cls] of Object.entries(MAP)) {
    const e = esc(style)
    if (cls === null) {
      html = html.split(` style="${style}"`).join('')
    } else {
      // class before style (attrs may sit between)
      html = html.replace(new RegExp(`class="([^"]*)"([^>]*?)\\s+style="${e}"`, 'g'), (_m, c, mid) => `class="${c} ${cls}"${mid}`)
      // style before class
      html = html.replace(new RegExp(`style="${e}"([^>]*?)\\s+class="([^"]*)"`, 'g'), (_m, mid, c) => `${mid.trimStart() ? mid + ' ' : ''}class="${c} ${cls}"`)
      // standalone (no class on the element)
      html = html.replace(new RegExp(`style="${e}"`, 'g'), `class="${cls}"`)
    }
  }
  const after = (html.match(/style="/g) || []).length
  if (after !== before) { writeFileSync(path, html, 'utf8'); totalRemoved += (before - after); console.log(`  ${f}: ${before} → ${after} inline styles`) }
}
console.log(`\nremoved ${totalRemoved} inline style attributes`)
